kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
  namespace: "autops"
spec:
  global:
    site: "datadoghq.com"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
      appSecret:
        secretName: "datadog-secret"
        keyName: "app-key"
  features:
    apm:
      enabled: true
      instrumentation:
        enabled: true
        targets:
          - name: "autops-target"
            namespace: "autops"
            ddTraceVersions:
              python: "3"
            selector:
              matchLabels:
                app: "autops"
    logCollection:
      enabled: true
      containerCollectAll: true
    processMonitoring:
      enabled: true
    networkMonitoring:
      enabled: true
    liveProcessCollection:
      enabled: true
  override:
    nodeAgent:
      env:
        - name: DD_LOGS_ENABLED
          value: "true"
        - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
          value: "true"
        - name: DD_PROCESS_AGENT_ENABLED
          value: "true"
        - name: DD_CONTAINER_EXCLUDE
          value: "name:datadog-agent"
      tolerations:
        - operator: Exists 